name: Build and Create Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
          architecture: 'x64'

      - name: Build with Maven
        run: mvn -B package --file BeanQuizCli/pom.xml

      - name: Create Runtime Image with JLink
        run: |
          mkdir -p target/image
          jlink --add-modules java.base,java.sql,java.desktop,java.logging,java.management,java.naming,java.net.http,java.security.jgss,java.xml,java.xml.bind --output target/image --strip-debug --compress 2

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bean-quiz-runtime-image
          path: target/image
