name: Build, Package, and Create Runnable JRE

# on:
#   push:
#     branches:
#       - main

on:
  push:
    branches: [ "fix/cli-package-pipeline" ]
    paths:
      - 'BeanQuizCli/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
          architecture: 'x64'

      - name: Build with Maven
        run: mvn -B package --file BeanQuizCli/pom.xml

      - name: Create Runnable JRE
        run: |
          # Get the name of the JAR file dynamically
          JAR_FILE=$(find target -name "*.jar" | head -n 1)
          jlink --add-modules "$JAR_FILE" --output my-runtime-image
          # Optional: Create an executable binary
          jlink --add-modules "$JAR_FILE" --output my-runtime-image --launcher

      - name: Archive JAR and JRE
        uses: actions/upload-artifact@v2
        with:
          name: my-artifacts
          path: |
            target/*.jar
            my-runtime-image
