name: Build and Create Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          sudo wget https://github.com/AdoptOpenJDK/openjdk16-binaries/releases/download/jdk-16.0.2%2B7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
          sudo tar xfvz OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz -C /usr/local
          sudo update-alternatives --install /usr/bin/java java /usr/local/jdk-16.0.2_7/bin/java 100
          java -version

      - name: Build with Maven
        run: mvn -B package --file BeanQuizCli/pom.xml

      - name: Create Executable JAR
        run: jar -cvfe beanquizapp.jar za.co.bbd.cli.beanquiz.App .

      - name: Create Windows Executable
        run: |
          sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev libxrandr-dev libxi-dev
          sudo apt-get install -y libgtk2.0-dev libpulse-dev libfreetype6-dev libasound2-dev
          jpackage --input . --main-jar beanquizapp.jar --type exe --name BeanQuizApp

      - name: List files
        run: ls -l

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bean-quiz-executable
          path: beanquizapp.jar, BeanQuizApp.exe
