name: Build and Create Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sdkman
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"

      - name: Setup SDKMAN in the current shell
        run: source "$HOME/.sdkman/bin/sdkman-init.sh"

      - name: Install JDK 21
        run: |
          sdk install java 21.0.0-open

      - name: Build with Maven
        run: mvn -B package --file BeanQuizCli/pom.xml

      - name: Create Executable JAR
        run: jar -cvfe beanquizapp.jar za.co.bbd.cli.beanquiz.App .

      - name: Create Windows Executable
        run: |
          sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev libxrandr-dev libxi-dev
          sudo apt-get install -y libgtk2.0-dev libpulse-dev libfreetype6-dev libasound2-dev
          jpackage --input . --main-jar beanquizapp.jar --type exe --name BeanQuizApp

      - name: List files
        run: ls -l

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bean-quiz-executable
          path: beanquizapp.jar, BeanQuizApp.exe
