name: Build and Create Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build with Maven
        run: mvn -B package --file BeanQuizCli/pom.xml

      - name: Create Executable JAR
        run: jar -cvfe beanquizapp.jar za.co.bbd.cli.beanquiz.App .

      - name: Install Launch4j
        run: sudo apt-get install -y launch4j

      - name: Create Windows Executable
        run: launch4j --jar beanquizapp.jar --header-type console --outfile BeanQuizApp.exe

      - name: List files
        run: ls -l

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bean-quiz-executable
          path: BeanQuizApp.exe
