name: Build and Create Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file BeanQuizCli/pom.xml

      - name: Create Executable JAR
        run: jar -cvfe beanquizapp.jar za.co.bbd.cli.beanquiz.App .

      - name: Create Windows Executable
        run: jpackage --input . --main-jar beanquizapp.jar --type exe --name BeanQuizApp

      - name: List files
        run: ls -l

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bean-quiz-executable
          path: BeanQuizApp.exe
