name: Build and Create Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build with Maven
        run: mvn -B package --file BeanQuizCli/pom.xml

      - name: Create Executable JAR
        run: jar -cvfe beanquizapp.jar za.co.bbd.cli.beanquiz.App .

      - name: Download Launch4j
        run: |
          wget https://sourceforge.net/projects/launch4j/files/launch4j-3/3.14/launch4j-3.14-linux-x64.tgz/download -O launch4j.tgz
          tar -xzf launch4j.tgz
          chmod +x launch4j-3.14-linux-x64/launch4j
          sudo mv launch4j-3.14-linux-x64/launch4j /usr/local/bin/
          rm -rf launch4j-3.14-linux-x64 launch4j.tgz

      - name: Create Windows Executable
        run: launch4j --jar beanquizapp.jar --header-type console --outfile BeanQuizApp.exe

      - name: List files
        run: ls -l

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: bean-quiz-executable
          path: BeanQuizApp.exe
