name: Flyway Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'Database/**'

jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Flyway Validate and Migrate
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: jdbc:postgresql://${{ secrets.DB_ENDPOINT }};encrypt=true;${{ secrets.DB_NAME }};trustServerCertificate=true;
          user: ${{ secrets.DB_USERNAME }}
          password: ${{ secrets.DB_PASSWORD }}
          locations: filesystem:./Database
        env:
          FLYWAY_VALIDATE_MIGRATION_NAMING: true