name: release client

on:
    push:
      branches: [ "main" ]
      paths:
        - 'BeanQuizCli/**'
    workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      permissions:
        contents: write

      steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: v${{ github.run_number }}
            release_name: Release ${{ github.run_number }}
            draft: false
            prerelease: false
      
      - name: build artifacts
        run: |
         cd BeanQuizCli
         mvn package 
         jpackage --input target/ --name beanquiz --main-jar BeanQuizCli-1.0-SNAPSHOT.jar --type deb
         
      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          path: BeanQuizCli/beanquiz_1.0_amd64.deb
          name: beanquiz_1.0_amd64.deb

      - name: Upload Instruction File
        uses: actions/upload-artifact@v3
        with:
          path: BeanQuizCli/instructions.txt
          name: instruction.txt   
