name: release client

on:
    push:
      branches: [ "main" ]
      paths:
        - 'BeanQuizCli/**'
    workflow_dispatch:

jobs:
  build-linux-installer:
      runs-on: ubuntu-latest
      permissions:
        contents: write

      steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            tag_name: v${{ github.run_number }}
            release_name: Release ${{ github.run_number }}
            draft: false
            prerelease: false
      
      - name: build artifacts
        run: |
         cd BeanQuizCli
         mvn package 
         jpackage --input target/ --name beanquiz --main-jar BeanQuizCli-1.0-SNAPSHOT.jar --type deb
         
      - name: Upload artifacts to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: BeanQuizCli/beanquiz_1.0_amd64.deb
          asset_name: beanquiz_1.0_amd64.deb
          asset_content_type: application/vnd.debian.binary-package

      - name: Upload Instruction File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: BeanQuizCli/instructions.txt
          asset_name: instruction.txt
          asset_content_type: text/plain
          
  build-windows-installer:
    name: Build Installer on Windows
    runs-on: windows-latest
    permissions:
        contents: write
    needs: [build-linux-installer]
        
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build artifacts
        run: |
          cd BeanQuizCli
          mvn package
          jpackage --input target --name beanquiz --main-jar BeanQuizCli-1.0-SNAPSHOT.jar --type exe --win-console
          ls

      - name: Get Release
        id: get_release
        run: |
            response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            https://api.github.com/repos/${{ github.repository }}/releases/latest)
            echo "::set-output name=release_data::$response"

      - name: Upload installer
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.get_release.outputs.release_url }}
          asset_path: BeanQuizCli/beanquiz-1.0.exe
          asset_name: beanquiz-1.0.exe
          asset_content_type: application/x-executable

